### ISSUE TITLE
SAfari browser not working percircle.js

### ISSUE THREAD

**Issue by RJRahevar** [toubou91/percircle#36] opened 2016-07-22 07:15 UTC
hello..
 i have create simple demo in asp.net ..
mozilla , crome  etc... browser working BUT SAFARI Browser not working 

please suggest me

**Comment by toubou91** [comment] 2016-07-22 18:06
Hey @RJRahevar , thanks for mentioning it.
Which version are you using? I have just downloaded 5.1.7 and everything seems to be working fine (or maybe it's just for me, because what I downloaded was a Safari version for Windows OS, which might apparently have some differences, in comparison to the actual one, used from OSX).

What difficulties have you encountered? Could you please attach screenshots or logs?

**Comment by toubou91** [comment] 2016-08-17 18:28
Closing this one, since no further feedback given and no reproduction scenario available on my machine.

**Closed by toubou91** 2016-08-17 18:28 UTC
